import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import DeviceDetector from "device-detector-js"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  async function download() {
    if (typeof window != "undefined") {
      try {
        const detector = new DeviceDetector()
        const device = detector.parse(window.navigator.userAgent)

        const platform = device.os?.name.toLowerCase()

        const res = await fetch(`/api/latest/${platform}`)
        const data = await res.json()

        if (res.status == 200) {
          const a = document.createElement("a")

          a.href = data.url
          a.download = data.name
          document.body.appendChild(a)
          a.click()
          document.body.removeChild(a)
        }
      } catch (err) {
        console.log(err)
      }
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <button
            className={styles.card}
            onClick={download}
          >
            <h2 className={inter.className}>
              Download
            </h2>
            <p className={inter.className}>
              Download App for your platform
            </p>
          </button>
        </div>
      </main>
    </>
  )
}
